name: Upload Website Files To S3 Bucket

on:
  push:
    branches:
    - main

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: shallwefootball/s3-upload-action@master
        with:
          aws_key_id: ${{ secrets.ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.SECRET_ACCESS_KEY }}
          aws_bucket: mykyta-nemov-task-bucket
          source_dir: ./
