name: Загрузка файлов веб-сайта в S3 Bucket

on:
  push:
    branches:
      - main

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: jakejarvis/s3-sync-action@master
        with:
          args: --delete --exclude "*" --include "index.html" --include "styles.css"
        env:
          AWS_S3_BUCKET: mykyta-nemov-task-bucket
          AWS_ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_ACCESS_KEY }}
          SOURCE_DIR: ./
